apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    project: my-project-cal-pod1
spec:
  containers:
    - name: my-container-cal-pod1
      image: sharjikahamed/mdcalculator
      ports:
        - containerPort: 3000